---
title: "Reproducable Research Project Template"
author: 'Mindy L. Mallory'
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: 
  md_document:
    toc: true
bibliography: bibliography.bib
---
[research project template](#Research Project Template)

# Research Project Template

This repository contains a template for a reproducable research project. The fundamental idea of reproducable research is that the steps that take your research from raw data to manuscript, thesis, or report should be fully automated. This way, your work can be checked by your advisor, mentors, collaborators, others working in your area, journal reviewers, and your future self. 

I became interested in reproducable research because I was tired of being terrified of my own analysis. I was constantly petrified someone would question my work and ask me to open the black box and verify what I did was correct; in some cases even being asked reproduce a result was terrifiying because I knew the convoluted path of data prep and cleaning that I took in arriving at my result. 

I read the book [Reproducable Research with R and RStudio](http://www.amazon.com/Reproducible-Research-Studio-Chapman-Hall/dp/1466572841) by Christopher Gandrud [-@gandrud2013reproducible], and I read a lot of blog posts and tutorials by [Karl Broman](http://kbroman.org/pages/software.html) and [Carl Boettiger](http://www.carlboettiger.info/2012/05/06/research-workflow.html) and I struck out on my own path to execute a reproducable research project from start to finish. The repository for that project is [here](https://github.com/mindymallory/BBOBAS), while I was successful in learning the basics of how r, rmarkdown, knitr, and pandoc combine to make reproducable research possible, you can tell just by looking at the project's Github repository that I failed miserably at making the project reproducable. This is because the repository is totally unorganized, and I am pretty sure I am the only one who could reproduce the results from this project. 
