---
output: 
  pdf_document:
    template: simple.latex 
    fig_caption: yes
documentclass: ajae
bibliography: bibliography.bib
---


```{r, warning = FALSE, message = FALSE, echo=FALSE}
library(xtable)
library(ggplot2)
library(ggfortify)
library(gridExtra)
source('data-raw/fetch-raw-data.R')
load('analysis-output/results.Rda')
```


# Tables and Figures

```{r, echo=FALSE, warning = FALSE, message = FALSE, results = "asis"}
t = list()
t[[1]] <- xtable(adf[[1]]@testreg, caption = "ADF Results for Corn")
t[[2]] <- xtable(adf[[2]]@testreg, caption = "ADF Results for Soybeans")
print.xtable(t[[1]], caption.placement = 'top', comment = FALSE)
```

```{r, echo=FALSE, warning = FALSE, message = FALSE, results = "asis"}
print.xtable(t[[2]], caption.placement = 'top', comment = FALSE)
```

```{r, echo=FALSE, warning = FALSE, message = FALSE, fig.cap = 'Corn and Soybean Prices' }
plot1 <- autoplot(CZ2016, ylab = "Corn Prices, cents/bu") + theme_bw()
plot2 <- autoplot(SX2016, ylab = "Soybean Prices, cents/bu") + theme_bw()
grid.arrange(plot1, plot2, ncol=1)
```
